jenkins:
  environment:
    LDAP_DOMAIN: "${LDAP_DOMAIN}"
    SMTP_USER: "${INITIAL_ADMIN_USER}@${LDAP_DOMAIN}"
    SMTP_PASSWORD: "${INITIAL_ADMIN_PASSWORD_PLAIN}"
    SMTP_HOST: "mail-server"
    SMTP_PORT: "25"
    SMTP_SYSAD_EMAIL: "jenkins@adop-core"
    ADOP_SMTP_ENABLED: "true"

mail-server:
  image: tvial/docker-mailserver:v2
  hostname: mail-server
  domainname: "${SMTP_DOMAIN}"
  net: "${CUSTOM_NETWORK_NAME}"
  restart: "always"
  container_name: mail-server
  ports:
  # Because port 25 may already be running on your host..
    - "9025:25"
    - "143:143"
    - "587:587"
    - "993:993"
  volumes:
    - maildata:/var/mail
    - ../../mail-config/:/tmp/docker-mailserver/
